#!/usr/bin/env python3
"""Compile the PUBLIC content tier into a single knowledge base for the chatbot.

Writes netlify/functions/knowledge.mjs exporting the KB as a JS string.
Only reads content/ (public tier) -- never content_internal/ -- so nothing
confidential can reach the public chatbot.
"""
import json
import os
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "content")
OUT = os.path.join(ROOT, "netlify", "functions", "lib", "knowledge.mjs")

FILES = [
    "profile.yaml",
    "projects.yaml",
    "leadership.yaml",
    "experience.yaml",
    "case_brain.yaml",
    "recognition.yaml",
    "about.yaml",
]


def main():
    files = FILES
    parts = [
        "Lizzy Wong - portfolio knowledge base.",
        "This is the complete, sanitized material about Lizzy Wong's professional background.",
        "",
    ]
    for fn in files:
        path = os.path.join(CONTENT, fn)
        if not os.path.exists(path):
            continue
        data = yaml.safe_load(open(path, encoding="utf-8"))
        if data is None:
            continue
        section = fn.replace(".yaml", "").replace("_", " ").upper()
        parts.append("=== %s ===" % section)
        parts.append(yaml.safe_dump(data, sort_keys=False, allow_unicode=True).strip())
        parts.append("")
    kb = "\n".join(parts)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_kb.py -- do not edit by hand.\n")
        f.write("export const KB = " + json.dumps(kb) + ";\n")
    print("Wrote %s (%d chars)" % (OUT, len(kb)))


if __name__ == "__main__":
    main()
